package:
  name: distutils-activate-mingw
  version: 2.3

build:
  number: 4
  skip: true  # [not win]

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - setuptools

outputs:
  - name: distutils-activate-mingw

  - name: libpython
    requirements:
      - distutils-activate-mingw

test:
  requires:
    - gcc_{{ target_platform }}
  files:
    - spam.c

about:
  home: https://github.com/conda-forge/libpython-feedstock
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A mingw-w64 import library for python??.dll (on Windows)

extra:
  feedstock-name: libpython
  recipe-maintainers:
    - chrisburr
    - isuruf
