package:
  name: libpython
  version: 2.2

build:
  number: 0
  skip: true  # [not win]

requirements:
  host:
    - python
    - m2w64-toolchain
    - setuptools
  run:
    - python
    - setuptools

test:
  requires:
    - m2w64-toolchain
  files:
    - spam.c

about:
  home: https://github.com/conda-forge/libpython-feedstock
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A mingw-w64 import library for python??.dll (on Windows)

extra:
  recipe-maintainers:
    - chrisburr
    - isuruf
