package:
  name: libpython
  version: 2.0

build:
  number: 1
  skip: true  # [not win]

requirements:
  host:
    - python
    - m2w64-toolchain
  run:
    - python

test:
  requires:
    - m2w64-toolchain
  files:
    - spam.c

about:
  license: Other
  license_family: Other
  summary: A mingw-w64 import library for python??.dll (on Windows)

extra:
  recipe-maintainers:
    - chrisburr
